# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Test Release scripts with dry run

on:
  release:
    types: [created]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Java setup docs:
    # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#installing-custom-java-package-type
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        # tools.jar removed from '9', '11'. see https://openjdk.java.net/jeps/220
        java-version: '8' 
        distribution: 'adopt'
        java-package: 'jdk' 
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file
   
    - run: printf "JAVA_HOME = $JAVA_HOME \n"
    
    - name: gpg key generation - transient
      run: |
        export GNUPGHOME="/home/runner/.gnupg"
        ls *
        cat >tempkey <<EOF
          %echo Generating a basic OpenPGP key
          Key-Type: DSA
          Key-Length: 1024
          Subkey-Type: ELG-E
          Subkey-Length: 1024
          Name-Real: J143 Bot
          Name-Comment: This is automation script
          Name-Email: j143+[bot]@protonmail.com
          Expire-Date: 0
          Passphrase: asdfghjkl
          # Do a commit here, so that we can later print "done" :-)
          %commit
          %echo done
        EOF
        gpg --batch --generate-key tempkey
    
    - run: |
        gpg --list-keys
        GPG_KEY_ID="$(gpg --list-keys | head -n 4 | tail -n 1 | sed 's/^ *//g')"
    
    - name: Run invoke script
      run: |
        cd $GITHUB_WORKSPACE
        printf "$GITHUB_WORKSPACE --> github workspace\n"
        git clone https://github.com/j143/systemds
        cd systemds
        ls *
        export GNUPGHOME="/home/runner/.gnupg"
        ls $GNUPGHOME
        GPG_KEY_ID="$(gpg --list-keys | head -n 4 | tail -n 1 | sed 's/^ *//g')"
        export GPG_KEY=$GPG_KEY_ID
        bash $GITHUB_WORKSPACE/do-release.sh
      env:
        DRY_RUN: '1'
        GIT_BRANCH: 'master'
        RELEASE_VERSION: '2.1.0'
        ASF_USERNAME: 'firstname'
        GIT_NAME: 'Firstname Lastname'
        GIT_EMAIL: 'j143+[bot]@protonmail.com'
        CORRECT_RELEASE_INFO: '1'
        ASF_PASSWORD: 'asdfghjkl' # wrong password, only to run this workflow
        GPG_PASSPHRASE: 'asdfghjkl' # wrong passphrase, only to run this workflow

#     - name: Build with Maven
#       run: mvn -B package --file pom.xml

#     - name: Publish to GitHub Packages Apache Maven
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
